apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: databases
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27019
    name: mongo-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dpt
  namespace: databases
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec: 
      containers:
      - image: mongo:bionic
        name: mongodb
        ports:
        - name: mongo
          containerPort: 27017
        env:
          - name:  MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name:  mongodb-initdb
                key:  user
          - name:  MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mongodb-initdb
                key:  password
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
            claimName: mongo-pvc