apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: databases
spec:
  selector:
    app: mysql
  ports:
  - port: 12306
    targetPort: 3306
    name: mysql-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: databases
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dpt
  namespace: databases
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
      - image: mysql:8
        name: mysql
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
          - name:  MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mysql-root-password
                key:  password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
            claimName: mysql-pv-claim
