apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: databases
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: databases
spec:
  type: ExternalName
  externalName: postgres.databases.svc.cluster.local
  selector:
    app: postgres
  ports:
  - port: 5432
    name: postgres-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: databases
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec: 
      containers:
      - image: postgres:11-alpine
        name: postgresql
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: postgres
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: "/mnt/data"
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
            claimName: postgres
