apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: development
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: production
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: toolbox
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: databases
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
