apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: devlopment
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: production
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  managedFields:
    - apiVersion: v1
  name: toolbox
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
