apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph
type: Opaque
data:
  userID: Y3NpLXJkYi1wcm92aXNpb25lcgo=
  userKey: Nnl1VmhWMnkwaTh4NmFuQTRYYmROTTlMSkl1YnpZMU8K
  clusterID: cm9vay1jZXBoCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph
type: Opaque
data:
  userID: Y3NpLXJkYi1ub2RlCg==
  userKey: Nnl1VmhWMnkwaTh4NmFuQTRYYmROTTlMSkl1YnpZMU8K
---
